name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    name: Build Backend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Run tests
      run: mvn test
      
    - name: Build Docker image
      run: docker build -t task-manager-backend:${{ github.sha }} .
      
    - name: List artifacts
      run: ls -la target/
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-jar-${{ github.sha }}
        path: backend/target/*.jar
        retention-days: 5
